server:
  port: 8080
mybatis:
  type-aliases-package: com.shop.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.shop.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiqu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
  application:
    name: shop
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 0
security:
  basic:
    enabled: false

shop:
  weChat:
    appId: wxbb51bdc0325f54c1
    appSecret: 586d9ab219cdc213f55a44395ba17e8c

  qiniuyun:
    key:
      accessKey: REbNa-8m8K8tFt_44a93F_4Kqs3ZDEF-okAk534e
      accessSecretKey: uo4P7VCa-hmBFir-Guhj6GbF1lQEsMgFyB2VVDDe
    oss:
      privateHost: cdn.chuxinbuwang.com
      publicHost: cdn.chuxinbuwang.com
    picPath: pic/
    picBuket: bxw_pic
